"""CLI exit codes per SRS §19."""

SUCCESS = 0
GENERAL_ERROR = 1
INVALID_ARGUMENTS = 2
BOOTSTRAP_FAILED = 3
PROVIDER_VALIDATION_FAILED = 4
MONGODB_CONNECTION_FAILED = 5
TELEGRAM_CONNECTION_FAILED = 6
